twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    paths:
        'public/images': images
        'public/css': styles
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
